git add -f carpet.mat
git add -f ceiling.mat
git add -f compare_receiver_response.py
git add -f convert_comsol_nastran_to_gmsh.py
git add -f ExportWaveBasedRoomGolden.class
git add -f ExportWaveBasedRoomGolden.class.status
git add -f ExportWaveBasedRoomGolden.java
git add -f ExportWaveBasedRoomMesh.class
git add -f ExportWaveBasedRoomMesh.class.status
git add -f ExportWaveBasedRoomMesh.java
git add -f ExportWaveBasedRoomReceiverPoints.class
git add -f ExportWaveBasedRoomReceiverPoints.class.status
git add -f ExportWaveBasedRoomReceiverPoints.java
git add -f extract_comsol_golden.py
git add -f fit_wave_based_room_admittance.py
git add -f git_add.sh
git add -f main.py
git add -f MinerU_markdown_models.aco.wave_based_room.zh_CN_2078818541824344064.md
git add -f models.aco.wave_based_room.zh_CN.pdf
git add -f nx3nt3.mat
git add -f nx3nt3_smoke_compare_metrics.json
git add -f nx3nt3_smoke.mat
git add -f pressure_time_golden_comparison.png
git add -f README.md
git add -f result.mat
git add -f results_on_the_run.mat
git add -f sofa.mat
git add -f wall.mat
git add -f wave_based_room_admittance_carpet.zh_CN.txt
git add -f wave_based_room_admittance_ceiling.zh_CN.txt
git add -f wave_based_room_admittance_sofa.zh_CN.txt
git add -f wave_based_room_admittance_wall.zh_CN.txt
git add -f wave_based_room_boundary_groups.py
git add -f wave_based_room_comsol_golden.csv
git add -f wave_based_room_comsol_golden.mat
git add -f wave_based_room_comsol_tet_hmax0p163_hmin0p04.msh
git add -f wave_based_room_comsol_tet_hmax0p163_hmin0p04.nas
git add -f wave_based_room_golden_export.log
git add -f wave_based_room_golden_export_stdout.log
git add -f wave_based_room_mesh_conversion_report.json
git add -f wave_based_room_mesh_export_stdout.log
git add -f wave_based_room_receiver_export.log
git add -f wave_based_room_receiver_points.json